# Generated by Django 5.2.3 on 2025-08-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_full_name_user_unique_email_if_provided_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
